//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TimeAllocation.data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Assignment
    {
        public Assignment()
        {
            this.Assignment_Allocation = new HashSet<Assignment_Allocation>();
        }
    
        public int Assignment_ID { get; set; }
        public int PTR { get; set; }
        public string Client { get; set; }
        public string Product { get; set; }
        public string Priority { get; set; }
        public string Affected_Areas { get; set; }
        public Nullable<double> Dev_Estimate { get; set; }
        public Nullable<System.DateTime> Dev_Due_Date { get; set; }
        public string Dev_Status { get; set; }
        public string Developer { get; set; }
        public string Dev_Role { get; set; }
        public bool Dev_Assigned { get; set; }
        public Nullable<double> Hrs_Completed { get; set; }
        public Nullable<double> Hrs_Remaining { get; set; }
        public Nullable<System.DateTime> Release_Date { get; set; }
        public System.DateTime Add_Date { get; set; }
        public string Enhancement { get; set; }
        public bool Active { get; set; }
    
        public virtual ICollection<Assignment_Allocation> Assignment_Allocation { get; set; }
    }
}
