//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TimeAllocation.data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Assignment_Allocation
    {
        public int Allocation_ID { get; set; }
        public int Assignment_ID { get; set; }
        public System.DateTime Week_Ending { get; set; }
        public double Hrs { get; set; }
        public System.DateTime Add_Date { get; set; }
        public Nullable<System.DateTime> Change_Date { get; set; }
    
        public virtual Assignment Assignment { get; set; }
    }
}
