//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TimeAllocation.data
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_Assignment_Allocation
    {
        public int Assignment_ID { get; set; }
        public string Developer { get; set; }
        public int PTR { get; set; }
        public string Client { get; set; }
        public string Priority { get; set; }
        public string Dev_Due_Date { get; set; }
        public Nullable<double> Dev_Estimate { get; set; }
        public Nullable<double> Hrs_Completed { get; set; }
        public string Dev_Status { get; set; }
        public Nullable<double> C06_17_2016 { get; set; }
        public Nullable<double> C06_24_2016 { get; set; }
        public Nullable<double> C07_01_2016 { get; set; }
        public Nullable<double> C07_08_2016 { get; set; }
        public Nullable<double> C07_15_2016 { get; set; }
        public Nullable<double> C07_22_2016 { get; set; }
        public Nullable<double> Hrs_Remaining { get; set; }
    }
}
