//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TimeAllocation.data
{
    using System;
    using System.Collections.Generic;
    
    public partial class WeekEnding
    {
        public System.DateTime Week_Ending { get; set; }
        public int Week_Ending_ID { get; set; }
        public string Week_Ending_Text { get; set; }
    }
}
